### ISSUE TITLE
Phylogenetic placement on a ghost-tree

### ISSUE THREAD

**Issue by vmikk** [JTFouquier/ghost-tree#69] opened 2016-06-07 04:58 UTC
Dear Jennifer and ghost-tree team,
Is it possible to perform a phylogenetic placement of sequences on a ghost-tree (e.g., with [pplacer](http://matsen.fhcrc.org/pplacer/), [EPA](https://github.com/zhangjiajie/EPA-classifier), [SEPP](https://github.com/smirarab/sepp) or others)?
Or it is impossible in principle, because of a hybrid nature of this tree?

With best regards,
Vladimir

**Comment by JTFouquier** [comment] 2016-06-10 16:50
Hi @vmikk, sorry for the delay. 

I'm a bit confused by your question because ghost-tree was designed to build a phylogenetic tree using sequence data/phylogenetic information from a marker gene that provides high taxonomic resolution. I'm also not familiar with these specific methods and neither were some of my colleagues. Can you please expand/clarify your question?  

I'm not sure if you found the paper first or the tool, so here is the paper if you have not seen it. https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-016-0153-6

Thank you!

**Comment by vmikk** [comment] 2016-06-12 14:00
Hello Jennifer! Thank you for the reply.

Sorry, I should clarify my question.
The next step after obtaining of DNA sequences is the identification of species to which they belong. There are different approaches for identification – the most common are the similarity-based search (e.g. BLAST) or a Bayesian classification (e.g., RDP). However there is another approach that allows inferring the position of (short) reads on an existing phylogenetic tree – so called ‘phylogenetic placement’.

In brief, it is possible to find the placement of sequences of interest on a reference phylogenetic tree given that one have the sequences that were used to build this tree. This method does not assign names to query sequences, but instead it returns an assignment of the query sequences to edges of a phylogenetic tree.

If I understand it correctly, to perform phylogenetic placement one will need to specify the model of sequence evolution, which will be problematic for a hybrid tree. So the question was about the possibility of usage of the ghost-tree in such applications.

More about phylogenetic placement:
- [Matsen _et al_. BMC Bioinformatics 2010 11:538 DOI: 10.1186/1471-2105-11-538](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-538)
- [Zhang _et al_. Bioinformatics 2013 29:22 DOI: 10.1093/bioinformatics/btt499](http://bioinformatics.oxfordjournals.org/content/29/22/2869)

**Comment by vmikk** [comment] 2016-06-16 14:13
It seems that the problem is even more complicated.

Assume that one sequenced the SSU and wish to place it on a foundation tree from ghost-tree. It will be problematic because the sequences from SILVA (that were used to build the foundation tree) were gap- and entropy filtered and hence they are not directly comparable with the query sequences.

By the way, [here](http://www.polarmicrobes.org/?p=1635) and [here](http://www.polarmicrobes.org/?p=699) are short tutorials for phylogenetic placement for the 16S rRNA gene by Jeff Bowman. I hope that one day this approach will be easy accessible for fungi.

**Comment by JTFouquier** [comment] 2016-06-17 18:02
Hi @vmikk, I'll likely get to this on Sunday. I've been super busy getting ready for my wedding and honeymoon (1 week away), so I am sorry for the delay.

**Comment by JTFouquier** [comment] 2016-06-20 19:21
Thanks for putting so much thought into this and for the well wishes! I plan to do more development on this project in a few months after things calm down. I'll also be moving out of state, so I apologize if I am out of touch for a few months. Thank you!  -Jennifer

**Comment by JTFouquier** [comment] 2016-10-13 01:37
@vmikk... I'm closing this now. Did you need anything else with this issue?  Thanks!

**Closed by JTFouquier** 2016-10-13 01:37 UTC
